base:
  MIGRATIONS: ['src/database/migrations/**/*.ts']
  MIGRATIONS_DIR: src/database/migrations
  ENTITIES: ['src/api/models/**/*.ts']
  ENTITIES_DIR: src/api/models
  CONTROLLERS: ['src/api/controllers/**/*Controller.ts']
  MIDDLEWARES: ['src/api/middlewares/global/**/*Middleware.ts']
  INTERCEPTORS: ['src/api/interceptors/**/*Interceptor.ts']
  SUBSCRIBERS: ['src/api/subscribers/**/*Subscriber.ts']
  RESOLVERS: ['src/api/resolvers/**/*Resolver.ts']

development:
  ~compose: base

test:
  ~compose: base

production:
  ~compose: base
